# Generated by Django 3.0.2 on 2021-02-05 22:02

import assessments.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('order_id', models.IntegerField(default=1)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this Assessment.', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', help_text='Enter the Name of this Assessment', max_length=400, unique=True)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('complete_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('QUESTIONNAIRE_REVIEW', 'Questionnaire in Review'), ('VENDOR_SUBMIT', 'Submitted to Vendor'), ('IN_ANALYSIS', 'In Analysis'), ('REPORT_GENERATED', 'Report Generated'), ('ASSESSMENT_REVIEW', 'Assessment Under Review'), ('ASSESSMENT_COMPLETE', 'Assessment Complete')], default='CREATED', max_length=25)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentFrameworks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this Document.', primary_key=True, serialize=False, unique=True)),
                ('document', models.FileField(upload_to=assessments.models.user_directory_path)),
                ('uploadDate', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=500)),
                ('description', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('order_id', models.IntegerField(default=1)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this Framework.', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', help_text="Enter the Framework's First Name", max_length=200)),
                ('short_name', models.CharField(default='', help_text="Enter the Framework's First Name", max_length=50)),
                ('version', models.CharField(default='1.1', help_text="Enter the Framework's Version Number", max_length=3)),
                ('publication_date', models.DateField(default=datetime.date.today, help_text='Enter the date the framework was published')),
                ('controls_file', models.FileField(blank=True, upload_to=assessments.models.Framework.framework_based_upload_to)),
            ],
            options={
                'ordering': ['order_id'],
            },
        ),
        migrations.CreateModel(
            name='FrameworkControls',
            fields=[
                ('order_id', models.IntegerField(default=1)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this Framework Control.', primary_key=True, serialize=False, unique=True)),
                ('frameworkUUID', models.UUIDField()),
                ('function', models.CharField(blank=True, default='', help_text="Enter the Control's Function", max_length=50)),
                ('functionID', models.CharField(blank=True, default='', help_text="Enter the Control's FunctionID", max_length=6)),
                ('category', models.CharField(blank=True, default='', help_text="Enter the Control's Category", max_length=300)),
                ('categoryID', models.CharField(blank=True, default='', help_text="Enter the Control's CategoryID", max_length=6)),
                ('category_statement', models.CharField(blank=True, default='', help_text="Enter the Control's Category Statement", max_length=300)),
                ('subcategory', models.CharField(blank=True, default='', help_text="Enter the Control's SubCategory", max_length=300)),
                ('subcategoryID', models.CharField(blank=True, default='', help_text="Enter the Control's SubCategoryID", max_length=20)),
                ('control_statement', models.CharField(blank=True, default='', help_text='Enter the Control Statement', max_length=300)),
                ('default_question', models.CharField(blank=True, default='', help_text="Enter the Control's References", max_length=600)),
                ('reference', models.CharField(blank=True, default='', help_text="Enter the Control's References", max_length=300)),
                ('evidencefile', models.FileField(blank=True, upload_to='uploads')),
            ],
            options={
                'ordering': ['order_id'],
            },
        ),
        migrations.CreateModel(
            name='FrameworkSource',
            fields=[
                ('order_id', models.IntegerField(default=1)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this Framework Source.', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', help_text="Enter the Source's First Name", max_length=50)),
                ('acronym', models.CharField(default='', help_text="Enter the Source's Acronym", max_length=14)),
                ('url', models.CharField(default='', help_text="Enter the Source's Web Site URL", max_length=200)),
            ],
            options={
                'ordering': ['order_id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('order_id', models.IntegerField(default=1)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this Question.', primary_key=True, serialize=False, unique=True)),
                ('function', models.CharField(blank=True, default='', help_text="The Control's Function", max_length=50, null=True)),
                ('functionID', models.CharField(blank=True, default='', help_text="The Control's FunctionID", max_length=6, null=True)),
                ('category', models.CharField(blank=True, default='', help_text="The Control's Category", max_length=300, null=True)),
                ('categoryID', models.CharField(blank=True, default='', help_text="The Control's CategoryID", max_length=6, null=True)),
                ('category_statement', models.CharField(blank=True, default='', help_text="The Control's Category Statement", max_length=300, null=True)),
                ('subcategory', models.CharField(blank=True, default='', help_text="The Control's SubCategory", max_length=300, null=True)),
                ('subcategoryID', models.CharField(blank=True, default='', help_text="The Control's SubCategoryID", max_length=6, null=True)),
                ('control_statement', models.CharField(blank=True, default='', help_text='The Control Statement', max_length=300, null=True)),
                ('question', models.CharField(blank=True, default='', help_text='Enter the assessment question.', max_length=600, null=True)),
                ('answer', models.CharField(blank=True, default='', help_text='Enter the answer to assessment question.', max_length=600, null=True)),
                ('maturity', models.IntegerField(blank=True, default='1', help_text='Enter the maturity level for the question.', null=True)),
                ('compliance', models.BooleanField(blank=True, default=True, help_text="Is the vendor's response and evidence compliant with your framework control?", null=True)),
                ('notes', models.CharField(blank=True, default='', help_text='Enter any notes from the assessor.', max_length=400, null=True)),
                ('likelihood', models.CharField(blank=True, choices=[('VERY_LOW', 'Very Low'), ('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('VERY_HIGH', 'Very High')], default='MODERATE', max_length=12, null=True)),
                ('impact', models.CharField(blank=True, choices=[('VERY_LOW', 'Very Low'), ('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('VERY_HIGH', 'Very High')], default='MODERATE', max_length=12, null=True)),
                ('risk_rating', models.CharField(blank=True, default='MODERATE', max_length=12, null=True)),
                ('was_analyzed', models.BooleanField(blank=True, default=False, help_text='Did an analyst analyst this question?', null=True)),
            ],
            options={
                'ordering': ['order_id'],
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('order_id', models.IntegerField(default=1)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this Questionnaire.', primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['order_id'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('order_id', models.IntegerField(default=1)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this Report.', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, default='Report', max_length=200, unique=True)),
                ('executive_summary', models.CharField(blank=True, default='', help_text='Write in your executive summary here.', max_length=6000, null=True)),
                ('executive_findings', models.CharField(blank=True, default='', help_text='Write in your executive findings here.', max_length=2000, null=True)),
                ('executive_compliance_summary', models.CharField(blank=True, default='', help_text='Write in your executive findings summary here.', max_length=6000, null=True)),
                ('executive_risk_assessment_summary', models.CharField(blank=True, default='', help_text='Write in your executive risk assessment summary here.', max_length=6000, null=True)),
                ('executive_compliance_chart', models.ImageField(blank=True, upload_to=assessments.models.Report.framework_based_upload_to)),
                ('executive_risk_chart', models.ImageField(blank=True, upload_to=assessments.models.Report.framework_based_upload_to)),
                ('nc_controls', models.IntegerField(blank=True, null=True)),
                ('c_controls', models.IntegerField(blank=True, null=True)),
                ('publication_date', models.DateField(blank=True, default=datetime.date.today, help_text='Enter the date the report was published', null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='assessments.Assessment')),
            ],
        ),
    ]
