# Generated by Django 3.0.2 on 2021-02-05 22:02

import companies.models
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('order_id', models.IntegerField(default=1)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this User.', primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, default=1, related_name='group', to='auth.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('order_id', models.IntegerField(default=1)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this Company.', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', help_text='Enter the Company Name', max_length=100, unique=True)),
                ('address1', models.CharField(blank=True, default='', help_text='Enter the Company Address', max_length=200)),
                ('address2', models.CharField(blank=True, default='', max_length=200)),
                ('country', models.CharField(blank=True, default='', help_text='Enter the country in which the Company is located', max_length=50)),
                ('city', models.CharField(blank=True, default='', help_text='Enter the city in which the Company is located', max_length=50)),
                ('state', models.CharField(blank=True, default='', help_text='Enter the state in which the Company is located', max_length=2, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$', 'Invalid State Format')])),
                ('zip', models.CharField(blank=True, default='', help_text='Enter the zip code', max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]{5}(?:-[0-9]{4})?$', 'Invalid Zip Code Format')])),
                ('url', models.URLField(blank=True, default='', help_text='Enter the Company URL')),
                ('logo', models.URLField(blank=True, default='', help_text='Enter the URL where the Company Logo is located')),
                ('enrolled_date', models.DateField(blank=True, default=datetime.date.today, help_text="Today's date")),
                ('risk_rating', companies.models.EnField(blank=True, choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High')], default='MODERATE', max_length=12)),
                ('data_sensitivity_rating', companies.models.EnField(blank=True, choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High')], default='MODERATE', max_length=12)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('is_vendor', models.BooleanField(blank=True, default=True)),
                ('relationship_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='companies.Company')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='usercompany',
            field=models.ManyToManyField(blank=True, through='companies.CompanyUsers', to='companies.Company'),
        ),
    ]
